name: "queue-system"

services:
  queue_system:
    build: .
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped